name: Auto-Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 */3 * *' # runs every 3 days at midnight UTC
  workflow_dispatch: # allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout the fork repository
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          ref: main

      # Configure Git
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Add upstream remote
      - name: Add upstream remote
        run: git remote add upstream https://github.com/navnee1h/terminal-portfolio.git

      # Fetch upstream changes
      - name: Fetch upstream
        run: git fetch upstream

      # Merge upstream changes automatically, favoring upstream
      - name: Merge upstream changes
        run: |
          git merge upstream/main -X theirs --allow-unrelated-histories || git merge --abort

      # Push changes to fork
      - name: Push changes
        run: git push origin main
